version: 0.0.{build}
install:
- choco install -y InnoSetup
- choco install -y nuget.commandline
build_script:
- nuget restore VATRP.sln
- msbuild VATRP.sln /p:Configuration="Release"  /p:Targets="Build" /verbosity:quiet  /p:BuildInParallel=true /m
- set vatrpVersion=%APPVEYOR_BUILD_VERSION%
- set PATH="C:\Program Files (x86)\Inno Setup 5";%PATH%
- Call iscc Setup\vatrp_setup.iss
artifacts:
- path: VATRP.App\bin\*
  name: binary
- path: Setup\Out\*.exe
  name: Setup
deploy:
- provider: GitHub
  tag: v$(APPVEYOR_BUILD_VERSION)
  release: Appveyor Automated v$(APPVEYOR_BUILD_VERSION)-$(GIT_HASH)
  description: Release of version $(APPVEYOR_BUILD_VERSION) \n $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: 85zYs73xAspqCTY0Y19QCKgVZRrq1NuJ9LCLJx/rZ59vo00jRf2Rs6k81WYAj0yx
  prerelease: true
  on:
    branch: master
notifications:
- provider: Email
  to:
  - vatrp@vtcsecure.flowdock.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
